title: Tia Tuinstra
description: Hi, I'm Tia! Welcome to my website.
url: https://TiaTuinstra.github.io

markdown: kramdown
theme: null

# Navigation
nav:
  - title: Home
    url: /
  - title: Projects
    url: /projects/
  - title: Get in Touch
    url: /contact/
